name: CrystalBansql
main: me.devphp.CrystalBansql.Core
authors: [Devphp]
version: 1.0
commands:
  ban:
    description: Bannir un joueur
  tempban:
    description: Bannir temporairement
  pardon:
    description: Pardonner un jouer
  importban:
    description: Importante les données précédement exporter
  exportban:
    description: Exporte les donnée vers le fichier texte ban.txt